services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: elliotbraem/ping-subscription-service:latest@sha256:769964cdceb6b676facc598f50d470e7bc705f8f661eca950b674c92d9f7f2b7
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
